version: '3.9'

services:
    backend-dev:
        build:
            context: ./backend
            dockerfile: Dockerfile.dev
        container_name: backend_dev
        ports:
            - "5001:5001"
        volumes:
            - ./backend:/home/backend
        networks:
            app-network:
                aliases:
                    - backend_host
        links:
            - database-dev

    database-dev:
        image: mcr.microsoft.com/mssql/server:latest
        container_name: database_dev
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Pass123*
        ports:
            - "1433:1433"
        volumes:
            - ./database/dev:/var/opt/mssql
        networks:
            app-network:
                aliases:
                    - database_host

    frontend-dev:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        container_name: frontend_dev
        ports:
            - "8080:8080"
        volumes:
            - ./frontend:/home/frontend
        networks:
            app-network:
                aliases:
                    - frontend_host
        links:
            - backend-dev

networks:
    app-network:
        name: app-net-dev
        driver: bridge
        ipam:
            driver: default
