version: '3.9'

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        env_file:
            - ./backend/.env
        ports:
            - "5001:5001"
        networks:
            app-network:
                aliases:
                    - backend_host
        links:
            - database

    database:
        image: mcr.microsoft.com/mssql/server:latest
        container_name: database
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=Pass123*
        ports:
            - "1433:1433"
        volumes:
            - ./database/data:/var/opt/mssql
        networks:
            app-network:
                aliases:
                    - database_host

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        ports:
            - "8080:80"
        networks:
            app-network:
                aliases:
                    - frontend_host
        links:
            - backend

networks:
    app-network:
        name: app-net
        driver: bridge
        ipam:
            driver: default
